import Head from "next/head";
import {About} from '../components/About'
import {Introduction} from '../components/Introduction'
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="container ">
      <Head>
        <title>Welcome My Website </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
	  <Introduction/>
    <About/>
     </main>
    </div>
  );
}
