import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container m-5"></main>
      <footer className="container hover:cursor-pointer">
        <h1 className="text-heading"> Hello World from fikri </h1>
      </footer>
    </div>
  );
}
